config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :teams
  resources :project_photos
  resources :projects

  namespace :api do
    namespace :v1 do
      resources :projects, only: [ :index, :show ], defaults: { format: :json }
      resources :project_photos, only: [ :index, :show ], defaults: { format: :json }
      resources :teams, only: [ :index, :show ], defaults: { format: :json }
      get "projects/:id/photos" => "projects#photos", defaults: { format: :json }
      get "teams/:id/members" => "teams#members", defaults: { format: :json }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/project_photo.rb
class ProjectPhoto < ApplicationRecord
  has_one_attached :photo
  belongs_to :project
end

app/controllers/api/v1/project_photos_controller.rb
class Api::V1::ProjectPhotosController < ApplicationController
  def index
    @project_photos = ProjectPhoto.all
  end

  def show
    @project_photo = ProjectPhoto.find(params[:id])
  end
end

app/controllers/project_photos_controller.rb
class ProjectPhotosController < ApplicationController
  before_action :set_project_photo, only: %i[ show edit update destroy ]

  # GET /project_photos or /project_photos.json
  def index
    @project_photos = ProjectPhoto.all

    render :index, status: :ok
  end

  # GET /project_photos/1 or /project_photos/1.json
  def show
  end

  # GET /project_photos/new
  def new
    @project_photo = ProjectPhoto.new
  end

  # GET /project_photos/1/edit
  def edit
  end

  # POST /project_photos or /project_photos.json
  def create
    @project_photo = ProjectPhoto.new(project_photo_params)

    respond_to do |format|
      if @project_photo.save
        format.html { redirect_to project_photo_url(@project_photo), notice: "Project photo was successfully created." }
        format.json { render :show, status: :created, location: @project_photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_photos/1 or /project_photos/1.json
  def update
    respond_to do |format|
      if @project_photo.update(project_photo_params)
        format.html { redirect_to project_photo_url(@project_photo), notice: "Project photo was successfully updated." }
        format.json { render :show, status: :ok, location: @project_photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_photos/1 or /project_photos/1.json
  def destroy
    @project_photo.destroy!

    respond_to do |format|
      format.html { redirect_to project_photos_url, notice: "Project photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_photo
      @project_photo = ProjectPhoto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_photo_params
      params.require(:project_photo).permit(:title, :project_id, :photo)
    end
end

app/helpers/project_photos_helper.rb
module ProjectPhotosHelper
end

app/views/project_photos/_form.html.erb
<%= form_with(model: project_photo) do |form| %>
  <% if project_photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_photo.errors.count, "error") %> prohibited this project_photo from being saved:</h2>

      <ul>
        <% project_photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= collection_select(:project_photo, :project_id, Project.all, :id, :name, {:prompt => "Select Project"})%>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/project_photos/_project_photo.html.erb
<div id="<%= dom_id project_photo %>">
  <p>
    <strong>Project:</strong>
    <%= project_photo.project.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= project_photo.title %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= image_tag(project_photo.photo) %>
  </p>

</div>

app/views/project_photos/edit.html.erb
<% content_for :title, "Editing project photo" %>

<h1>Editing project photo</h1>

<%= render "form", project_photo: @project_photo %>

<br>

<div>
  <%= link_to "Show this project photo", @project_photo %> |
  <%= link_to "Back to project photos", project_photos_path %>
</div>

app/views/project_photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Project photos" %>

<h1>Project photos</h1>

<div id="project_photos">
  <% @project_photos.each do |project_photo| %>
    <%= render project_photo %>
    <p>
      <%= link_to "Show this project photo", project_photo %>
    </p>
  <% end %>
</div>

<%= link_to "New project photo", new_project_photo_path %>

app/views/project_photos/new.html.erb
<% content_for :title, "New project photo" %>

<h1>New project photo</h1>

<%= render "form", project_photo: @project_photo %>

<br>

<div>
  <%= link_to "Back to project photos", project_photos_path %>
</div>

app/views/project_photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project_photo %>

<div>
  <%= link_to "Edit this project photo", edit_project_photo_path(@project_photo) %> |
  <%= link_to "Back to project photos", project_photos_path %>

  <%= button_to "Destroy this project photo", @project_photo, method: :delete %>
</div>