config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :teams
  resources :project_photos
  resources :projects

  namespace :api do
    namespace :v1 do
      resources :projects, only: [ :index, :show ], defaults: { format: :json }
      resources :project_photos, only: [ :index, :show ], defaults: { format: :json }
      resources :teams, only: [ :index, :show ], defaults: { format: :json }
      get "projects/:id/photos" => "projects#photos", defaults: { format: :json }
      get "teams/:id/members" => "teams#members", defaults: { format: :json }
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :photo
  has_one :member_projects
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:team_id, :name, :title, :photo)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :team_id, style: "display: block" %>
    <%= collection_select(:member, :team_id, Team.all, :id, :name, {:prompt => "Select Team"})%>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Team:</strong>
    <%= member.team_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= member.title %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= image_tag(member.photo) %>
  </p>

</div>

app/views/members/edit.html.erb
<% content_for :title, "Editing member" %>

<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Members" %>

<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<% content_for :title, "New member" %>

<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>